### ISSUE TITLE
Dates RELEASE-NOTES?

### ISSUE THREAD

**Issue by waandershz** [SemanticMediaWiki/SemanticBreadcrumbLinks#13]
If I read https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/blob/master/RELEASE-NOTES.md I see 2015-03-10 for version 1.3.0 and 2015-12-19 for version 1.2.0. Should be 201**6**-03-10?

Also according to https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/releases latest version is 1.2.0?

**Comment by kghbln** [comment]
Thanks for the pointer! SBL 1.3.0 is [not yet out](https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/blob/master/SemanticBreadcrumbLinks.php#L25)

**Comment by JeroenDeDauw** [comment]
https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/pull/14
