### ISSUE TITLE
Resource Loader: Unexpected general module

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticBreadcrumbLinks#21]
### Setup and configuration

- MediaWiki 	1.28.0-rc.1 (79498f9) 01:05, 17. Nov. 2016
- PHP 	5.6.27-0+deb8u1 (apache2handler)
- MariaDB 	10.0.28-MariaDB-1~jessie
- Semantic MediaWiki	2.5.0-alpha (930b5f3) 08:34, 24. Nov. 2016
- Semantic Breadcrumb Links	1.3.0 (3437d28) 08:34, 24. Nov. 2016 

### Issue

The resourceloader log is throwing the following issues in masses:

```
2016-11-26 13:00:32 phalaris 0210020150926-02100_: Unexpected general module "ext.semanticbreadcrumblinks" in styles queue.
```
Initially reported in bulk at https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1977 though this one belongs here.

**Comment by mwjames** [comment]
Hopefully addressed with 37262a718e432596d612b1d9b5d6c30fcc09bcb1.

**Comment by kghbln** [comment]
> Hopefully addressed with 37262a7.

Affirmative. No more unexpected general modules! Thanks a lot!

**Comment by mwjames** [comment]
The change caused FOUC (Flash of unstyled content), hence splitting styles and JS (#22).

**Comment by kghbln** [comment]
> The change caused FOUC

Oops, I did not see that. Thanks for fixing further!
