### ISSUE TITLE
Make 1.4.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticBreadcrumbLinks#33]
- [x] Finalize release notes
- [x] Update "README"
- [x] Update "composer.json" (remove SMW 3.0 dev)
- [x] Update "SemanticBreadcrumbLinks.php" (version 1.4.0)
- [x] Create tag
- [x] Start development of new version 
  - [x] Update "SemanticBreadcrumbLinks.php" (version 1.5.0-alpha)
  - [x] Update "composer.json" (add SMW 3.0 dev)
- [x] Announce via mail
- [x] Do a release tweet on Twitter

**Comment by kghbln** [comment]
@mwjames Now that things appear to be cool ...

**Comment by mwjames** [comment]
> Now that things appear to be cool ...

Whenever your ready, as steady fast release roller, I'll have full confidence.
