### ISSUE TITLE
Breadcrumbs do not get generated

### ISSUE THREAD

**Issue by john-dederer** [SemanticMediaWiki/SemanticBreadcrumbLinks#43]
### Setup and configuration

- SMW version: 2.5.6
- SBL version: 1.4.0
- MW version: 1.30.0
- PHP: 7.0
- DB (MySQL etc.): MySQL

### Issue
I am following the installation guide from the repo, but the breadcrumbs are not getting generated. The pages have the attribute Has parent page, but do not have the breadcrumbs to this parent. Installed by using composer. The only thing that is shown is the link to the parent page below the title but the breadcrumb is not generated.

I used a fresh install of mediawiki and also tried it on a fresh vm from bitnami mediawiki.

**Comment by kghbln** [comment]
Thanks for reporting. I can confirm this for sandbox too which is currently running MW 1.31.0 On [this page](https://sandbox.semantic-mediawiki.org/wiki/Issue/2037/Has_property_description) I expect to get breadcrumbs showing [that page](https://sandbox.semantic-mediawiki.org/wiki/Issue/2037).

**Comment by kghbln** [comment]
It seems that the setting made in ["SemanticBreadcrumbLinks.php"](https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/blob/master/SemanticBreadcrumbLinks.php#L119) is not respected. What happens if you add the following to "LocalSettings.php":
```php
$egSBLPropertySearchPatternByNamespace = [
	NS_CATEGORY => [
		'_SUBC',
		'_SUBC',
		'_SUBC'
		],
	SMW_NS_PROPERTY => [
		'_SUBP',
		'_SUBP',
		'_SUBP'
		],
	NS_MAIN => [
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE
		],
	NS_HELP => [
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE
		]
	];
```
After I have done this the breadcrumbs are back up in sandbox, e.g. for the examples I stated in my above examples.

**Comment by kghbln** [comment]
Hmm, now the crumbs are gone again. :|

**Comment by john-dederer** [comment]
I got it running using the mediawiki package from [legoktm](https://www.mediawiki.org/wiki/User:Legoktm/Packages). The mediawiki version is 1.27 if this helps.

**Comment by kghbln** [comment]
Thanks for reporting back. I guess this has something to do with the MW version 1.27 vs 1.31. Let's wait for the developer to have a peep at this.

**Comment by mwjames** [comment]
> Let's wait for the developer to have a peep at this.

refs #47
