### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticBreadcrumbLinks#5]
@SemanticMediaWiki/testers Would appreciate some testing and feedback before pressing the 1.0 release button.  (Requires SMW 2.1)

**Comment by mitchelln** [comment]
I will test.

**Comment by JeroenDeDauw** [comment]
@mwjames want any help with the rel from my side?

@mitchelln any findings yet?

**Comment by mitchelln** [comment]
Unfortunately not. Hitting dependency issues upgrading from SMW 2.0 to 2.1. I'll keep you posted.

**Comment by JeroenDeDauw** [comment]
What kind of dependency issues?

**Comment by JeroenDeDauw** [comment]
@mitchelln ping

@mwjames Shall I create a tag and write a release email?

**Comment by mwjames** [comment]
> Shall I create a tag and write a release email?

I would be much obliged.

**Comment by JeroenDeDauw** [comment]
1.0.0 tag created

**Comment by kghbln** [comment]
When trying to fetch @dev I am only getting 6b0398e of January 5, 2015 and not the 1.0 release. There is probably something in the water?

**Comment by mwjames** [comment]
> o fetch @dev I am only getting 6b0398e of January 5, 2015 and not the 1.0 release. 

I just did:
```
$ composer require mediawiki/semantic-breadcrumb-links:@dev
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mediawiki/semantic-breadcrumb-links (dev-master e046701)
    Cloning e04670190894a8301d60152e4377e127ede64986

Writing lock file
Generating autoload files
```

that fetches the https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/commit/e04670190894a8301d60152e4377e127ede64986 commit and with:
```
$ composer require mediawiki/semantic-breadcrumb-links:~1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating mediawiki/semantic-breadcrumb-links (dev-master e046701 => 1.0.0)
    Checking out 97539a0ccbdd46756402e3b1469f3e973139379c

Writing lock file
Generating autoload files
```

obtaining the correct https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/commit/97539a0ccbdd46756402e3b1469f3e973139379c.

**Comment by kghbln** [comment]
Nope, just did an `$ composer update` again and all I am getting is January 5. `"mediawiki/semantic-breadcrumb-links": "@dev"` is in my "composer.json" as it is the case for 16 other extensions and this is the only one not updating. :(

**Comment by mwjames** [comment]
> Nope, just did an $ composer update again and all I am getting is January 5.

How about doing `composer require mediawiki/semantic-breadcrumb-links:@dev` first and then `composer update`?

**Comment by kghbln** [comment]
This did not help either. However, I removed the extension entirely and required it in a second step. Probably should have tried this in the first place. Now everything is in fluff. Do not ask me what happened here. Thanks!
