### ISSUE TITLE
 Notice: Use of undefined constant `SBL_PROP_PARENTPAGE`

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticBreadcrumbLinks#56]
### Setup and configuration

- PHP | 5.6.38-0+deb8u1 (apache2handler)
- MySQL | 5.5.60-0+deb8u1
- MediaWiki | 1.27.5 (3e66859)00:06, 21. Sep. 2018
- Semantic MediaWiki | 3.0.0-rc.2 (d0ca031) 16:13, 2. Okt. 2018
- Semantic Breadcrumb Links | 2.0.0-alpha (69b7b6b) 13:19, 30. Sep. 2018

### Issue
 ```
Notice: Use of undefined constant SBL_PROP_PARENTPAGE - assumed 'SBL_PROP_PARENTPAGE' in /.../w/LocalSettings.php on line 690
```
This notice is emitted for all four lines for `NS_MAIN` holding `SBL_PROP_PARENTPAGE`.

### Steps to reproduce
```php
## Semantic Breadcrumb Links
wfLoadExtension( 'SemanticBreadcrumbLinks' );
$egSBLPageTitleToHideSubpageParent = false;
$egSBLPropertySearchPatternByNamespace = [
	NS_CATEGORY => [
		'_SUBC',
		'_SUBC',
		'_SUBC'
		],
	SMW_NS_PROPERTY => [
		'_SUBP',
		'_SUBP',
		'_SUBP'
		],
	NS_MAIN => [
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE
		],
	NS_HELP => [
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE,
		SBL_PROP_PARENTPAGE
		]
	];
```
An additional question: Do I have to redefine the whole array of arrays or is there a way to add a search strategy e.g. for `NS_MAIN` without touching the other arrays?

**Comment by JeroenDeDauw** [comment]
The constant is defined in `SemanticBreadcrumbLinks::initExtension` and used in `SemanticBreadcrumbLinks::onExtensionFunction`.

This error means the constant is used before it is defined. Either onExtensionFunction should not be called before initExtension... or the constant definition should be moved.

**Comment by kghbln** [comment]
I again spend over half an hour on this issue. I'd rather spend this time elsewhere on this project than looping back every half year. Is there a way to fix this? I am now on 
* MediaWiki | 1.31.6 (0841683)
* PHP | 7.3.15 (cgi-fcgi)
* MySQL | 5.6.40-84.0-log
* ICU | 4.8.1.1
* Semantic MediaWiki | 3.1.5 (d9fa46a) 00:14, 8 February 2020
* Semantic Breadcrumb Links | 2.0.0 (9f62cbb) 22:15, 6 October 2018

**Comment by kghbln** [comment]
@mwjames It will be super cool to get a fix for this.
