### ISSUE TITLE
Invalid usage of PHP that makes my IDE mad

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticBreadcrumbLinks#6]
![varref](https://cloud.githubusercontent.com/assets/146040/6198229/d843749c-b3f7-11e4-84a8-57a152ce539c.png)

**Comment by mwjames** [comment]
[0] uses the same `DIRECTORY_SEPARATOR . 'extensions' . DIRECTORY_SEPARATOR, __DIR__, 2`

https://github.com/wmde/ValueView/blob/44ca1b31a172130224ffc707657558690ec03d45/tests/src/experts/resources.php

**Comment by JeroenDeDauw** [comment]
Think the issue is passing the explode result into end

**Comment by mwjames** [comment]
Fixed with ba05aee154
